import { ItemRarity, QuestType, SkillDamageKind, SkillElement } from '@prisma/client';

export const skillDefinitions = [
  {
    id: 'slash',
    name: 'Slash',
    description: 'A fast melee strike (physical).',
    requiredLevel: 1,
    requiredSkill: null,
    baseDamage: 0,
    manaCost: 0,
    cooldownMs: 0,
    damageKind: SkillDamageKind.PHYSIC,
    element: SkillElement.NONE,
  },
  {
    id: 'firebolt',
    name: 'Firebolt',
    description: 'Hurl a fireball that explodes on impact, damaging all enemies in a 5×5 area.',
    requiredLevel: 2,
    requiredSkill: null,
    baseDamage: 60,
    manaCost: 12,
    cooldownMs: 0,
    damageKind: SkillDamageKind.MAGIC,
    element: SkillElement.FIRE,
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    description: 'Conjure a 5×5 ice storm. Every 0.2s an ice shard falls in the area for 2s.',
    requiredLevel: 4,
    requiredSkill: null,
    baseDamage: 22,
    manaCost: 30,
    cooldownMs: 0,
    damageKind: SkillDamageKind.MAGIC,
    element: SkillElement.COLD,
  },
];

export const itemDefinitions = [
  // ─── Consumable potions (HP / MP, 5 levels each) ────────────────────────
  // basePower is repurposed to hold the heal amount. They are NOT rolled by
  // the regular rollItem flow — see rollPotionForMonsterLevel().
  { id: 'hp_potion_1', name: 'Minor Healing Flask', slot: 'potion_hp', basePower: 40, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_hp_1' },
  { id: 'hp_potion_2', name: 'Healing Flask', slot: 'potion_hp', basePower: 100, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_hp_2' },
  { id: 'hp_potion_3', name: 'Greater Healing Flask', slot: 'potion_hp', basePower: 250, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_hp_3' },
  { id: 'hp_potion_4', name: 'Major Healing Flask', slot: 'potion_hp', basePower: 600, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_hp_4' },
  { id: 'hp_potion_5', name: 'Grand Healing Elixir', slot: 'potion_hp', basePower: 2000, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_hp_5' },
  { id: 'mp_potion_1', name: 'Minor Mana Flask', slot: 'potion_mp', basePower: 20, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_mp_1' },
  { id: 'mp_potion_2', name: 'Mana Flask', slot: 'potion_mp', basePower: 50, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_mp_2' },
  { id: 'mp_potion_3', name: 'Greater Mana Flask', slot: 'potion_mp', basePower: 125, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_mp_3' },
  { id: 'mp_potion_4', name: 'Major Mana Flask', slot: 'potion_mp', basePower: 300, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_mp_4' },
  { id: 'mp_potion_5', name: 'Grand Mana Elixir', slot: 'potion_mp', basePower: 1000, minLevel: 1, maxLevel: 99, rarity: ItemRarity.WHITE, icon: 'potion_mp_5' },

  { id: 'rusty_sword', name: 'Rusty Sword', slot: 'weapon', basePower: 8, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'sword' },
  { id: 'iron_sabre', name: 'Iron Sabre', slot: 'weapon', basePower: 11, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'sword' },
  { id: 'azure_dagger', name: 'Azure Dagger', slot: 'weapon', basePower: 13, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'sword' },
  { id: 'sunsteel_blade', name: 'Sunsteel Blade', slot: 'weapon', basePower: 16, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'sword' },
  { id: 'mythic_firstfang', name: 'Firstfang (Mythic)', slot: 'weapon', basePower: 22, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'sword' },
  { id: 'wolf_blade', name: 'Wolf Blade', slot: 'weapon', basePower: 14, minLevel: 3, maxLevel: 8, rarity: ItemRarity.BLUE, icon: 'sword' },
  { id: 'hunter_mail', name: 'Hunter Mail', slot: 'armor', basePower: 10, minLevel: 2, maxLevel: 7, rarity: ItemRarity.GREEN, icon: 'armor' },
  { id: 'scout_vest', name: 'Scout Vest', slot: 'armor', basePower: 9, minLevel: 1, maxLevel: 4, rarity: ItemRarity.BLUE, icon: 'armor' },
  { id: 'gilded_mail', name: 'Gilded Mail', slot: 'armor', basePower: 13, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'armor' },
  { id: 'mythic_boneshard_mail', name: 'Boneshard Mail (Mythic)', slot: 'armor', basePower: 18, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'armor' },
  { id: 'cloth_cap', name: 'Cloth Cap', slot: 'helmet', basePower: 6, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'helmet' },
  { id: 'sturdy_cap', name: 'Sturdy Cap', slot: 'helmet', basePower: 7, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'helmet' },
  { id: 'skyhood', name: 'Skyhood', slot: 'helmet', basePower: 8, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'helmet' },
  { id: 'halo_cap', name: 'Halo Cap', slot: 'helmet', basePower: 10, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'helmet' },
  { id: 'mythic_veil_of_dawn', name: 'Veil of Dawn (Mythic)', slot: 'helmet', basePower: 14, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'worn_pants', name: 'Worn Pants', slot: 'legs', basePower: 6, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'legs' },
  { id: 'trail_pants', name: 'Trail Pants', slot: 'legs', basePower: 7, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'legs' },
  { id: 'river_stride_pants', name: 'River Stride Pants', slot: 'legs', basePower: 8, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'legs' },
  { id: 'goldthread_pants', name: 'Goldthread Pants', slot: 'legs', basePower: 10, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'legs' },
  { id: 'mythic_gravetread_legs', name: 'Gravetread Legs (Mythic)', slot: 'legs', basePower: 14, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'legs' },
  { id: 'leather_gloves', name: 'Leather Gloves', slot: 'hands', basePower: 5, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'hands' },
  { id: 'hunter_gloves', name: 'Hunter Gloves', slot: 'hands', basePower: 6, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'hands' },
  { id: 'stormweave_gloves', name: 'Stormweave Gloves', slot: 'hands', basePower: 7, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'hands' },
  { id: 'gilded_grips', name: 'Gilded Grips', slot: 'hands', basePower: 9, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'hands' },
  { id: 'mythic_hand_of_ember', name: 'Hand of Ember (Mythic)', slot: 'hands', basePower: 13, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'hands' },
  { id: 'old_boots', name: 'Old Boots', slot: 'feet', basePower: 5, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'feet' },
  { id: 'wanderer_boots', name: 'Wanderer Boots', slot: 'feet', basePower: 6, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'feet' },
  { id: 'windstep_boots', name: 'Windstep Boots', slot: 'feet', basePower: 7, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'feet' },
  { id: 'sunwalk_boots', name: 'Sunwalk Boots', slot: 'feet', basePower: 9, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'feet' },
  { id: 'mythic_ashwalkers', name: 'Ashwalkers (Mythic)', slot: 'feet', basePower: 13, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'feet' },
  { id: 'copper_ring', name: 'Copper Ring', slot: 'ring', basePower: 7, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'ring' },
  { id: 'jade_ring', name: 'Jade Ring', slot: 'ring', basePower: 8, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'ring' },
  { id: 'sapphire_ring', name: 'Sapphire Ring', slot: 'ring', basePower: 9, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'ring' },
  { id: 'sunseal_ring', name: 'Sunseal Ring', slot: 'ring', basePower: 11, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'ring' },
  { id: 'mythic_oathband', name: 'Oathband (Mythic)', slot: 'ring', basePower: 15, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'bone_amulet', name: 'Bone Amulet', slot: 'amulet', basePower: 7, minLevel: 1, maxLevel: 4, rarity: ItemRarity.WHITE, icon: 'amulet' },
  { id: 'fern_amulet', name: 'Fern Amulet', slot: 'amulet', basePower: 8, minLevel: 2, maxLevel: 6, rarity: ItemRarity.GREEN, icon: 'amulet' },
  { id: 'azure_talisman', name: 'Azure Talisman', slot: 'amulet', basePower: 9, minLevel: 2, maxLevel: 7, rarity: ItemRarity.BLUE, icon: 'amulet' },
  { id: 'golden_charm', name: 'Golden Charm', slot: 'amulet', basePower: 11, minLevel: 1, maxLevel: 4, rarity: ItemRarity.YELLOW, icon: 'amulet' },
  { id: 'mythic_starcore', name: 'Starcore (Mythic)', slot: 'amulet', basePower: 15, minLevel: 1, maxLevel: 4, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'storm_charm', name: 'Storm Charm', slot: 'amulet', basePower: 18, minLevel: 5, maxLevel: 10, rarity: ItemRarity.YELLOW, icon: 'amulet' },
  { id: 'mythic_set_core', name: 'Mythic Set Core', slot: 'relic', basePower: 30, minLevel: 8, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'relic' },
  // Mythic set items (dropable; set bonuses are attached via affixJson in rollItem)
  { id: 'set_storm_ring', name: 'Hexenring', slot: 'ring', basePower: 18, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_storm_amulet', name: 'Storm Whisper', slot: 'amulet', basePower: 18, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_storm_helm', name: 'Crown of Static', slot: 'helmet', basePower: 18, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_ashen_blade', name: 'Ashrend', slot: 'weapon', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'sword' },
  { id: 'set_ashen_mail', name: 'Cinderplate', slot: 'armor', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'armor' },
  { id: 'set_ashen_boots', name: 'Ashwalkers', slot: 'feet', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'feet' },
  { id: 'set_ashen_gloves', name: 'Coalgrips', slot: 'hands', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'hands' },
  { id: 'set_dawn_helm', name: 'Veil of Dawn', slot: 'helmet', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_dawn_ring', name: 'Dawn Oathband', slot: 'ring', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_grave_amulet', name: 'Grave Sigil', slot: 'amulet', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_grave_legs', name: 'Rootbound Legs', slot: 'legs', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'legs' },
  { id: 'set_grave_gloves', name: 'Miretouch', slot: 'hands', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'hands' },
  { id: 'set_grave_boots', name: 'Bogsteps', slot: 'feet', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'feet' },
  { id: 'set_grave_helm', name: 'Wreath of Thorns', slot: 'helmet', basePower: 20, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_sky_blade', name: 'Skybreak', slot: 'weapon', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'sword' },
  { id: 'set_sky_mail', name: 'Cloudmail', slot: 'armor', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'armor' },
  { id: 'set_sky_helm', name: 'Aetherhood', slot: 'helmet', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_sky_legs', name: 'Galestride Pants', slot: 'legs', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'legs' },
  { id: 'set_sky_gloves', name: 'Skyweave Gloves', slot: 'hands', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'hands' },
  { id: 'set_sky_boots', name: 'Windwalkers', slot: 'feet', basePower: 24, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'feet' },
  { id: 'set_oath_ring', name: 'Iron Oathband', slot: 'ring', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_oath_amulet', name: 'Oath Pendant', slot: 'amulet', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_oath_mail', name: 'Oathkeeper Mail', slot: 'armor', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'armor' },
  { id: 'set_ember_blade', name: 'Emberfang', slot: 'weapon', basePower: 21, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'sword' },
  { id: 'set_ember_amulet', name: 'Cinder Charm', slot: 'amulet', basePower: 21, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_ember_gloves', name: 'Flamegrips', slot: 'hands', basePower: 21, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'hands' },
  { id: 'set_ember_boots', name: 'Coalsteps', slot: 'feet', basePower: 21, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'feet' },
  { id: 'set_mirror_ring', name: 'Mirror Ring', slot: 'ring', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_mirror_helm', name: 'Mirror Visor', slot: 'helmet', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_mirror_legs', name: 'Mirrorstride', slot: 'legs', basePower: 19, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'legs' },
  { id: 'set_wyrm_amulet', name: 'Wyrm Sigil', slot: 'amulet', basePower: 23, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_wyrm_ring', name: 'Wyrm Loop', slot: 'ring', basePower: 23, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_wyrm_blade', name: 'Wyrmfang', slot: 'weapon', basePower: 23, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'sword' },
  { id: 'set_wyrm_helm', name: 'Wyrm Crown', slot: 'helmet', basePower: 23, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_star_ring', name: 'Star Ring', slot: 'ring', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'ring' },
  { id: 'set_star_amulet', name: 'Starcore', slot: 'amulet', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'amulet' },
  { id: 'set_star_helm', name: 'Starhood', slot: 'helmet', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'helmet' },
  { id: 'set_star_mail', name: 'Starbound Mail', slot: 'armor', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'armor' },
  { id: 'set_star_boots', name: 'Starsteps', slot: 'feet', basePower: 22, minLevel: 1, maxLevel: 10, rarity: ItemRarity.MYTHIC, icon: 'feet' },
];

export const questDefinitions = [
  {
    id: 'q_kill_wolves',
    title: 'Thin The Pack',
    description: 'Kill 5 wolves in Ember Hollow.',
    type: QuestType.KILL_ENEMIES,
    targetValue: 5,
    targetKey: 'wolf',
    rewardExp: 40,
    rewardGold: 20,
  },
  {
    id: 'q_collect_blue',
    title: 'Treasure Hunter',
    description: 'Collect 1 blue item.',
    type: QuestType.COLLECT_ITEMS,
    targetValue: 1,
    targetKey: 'BLUE',
    rewardExp: 55,
    rewardGold: 25,
  },
];

export const dungeons = [
  { key: 'ember_hollow', zone: 'Ember Hollow', difficulty: 1, bossId: 'boss_ember' },
  { key: 'crypt_of_ashes', zone: 'Crypt of Ashes', difficulty: 2, bossId: 'boss_ash' },
];
